# Generated by Django 5.1.1 on 2024-09-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleClass', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('codeClasse', models.CharField(max_length=10)),
                ('creationDateClasse', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registrationId', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('role', models.CharField(choices=[('s', 'student'), ('t', 'teacher')], default='-', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='correction_TD_TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creationDateTdTp', models.DateField()),
                ('corrFile', models.FileField(null=True, upload_to='documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=50)),
                ('creationDateCourse', models.DateField()),
                ('courseFile', models.FileField(null=True, upload_to='documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTd', models.CharField(max_length=50)),
                ('creationDateTd', models.DateField()),
                ('tdFile', models.FileField(null=True, upload_to='documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creationDateTodo', models.DateField()),
                ('TodoTFile', models.FileField(null=True, upload_to='documents')),
                ('TodoSFile', models.FileField(null=True, upload_to='documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTp', models.CharField(max_length=50)),
                ('creationDateTp', models.DateField()),
                ('tpFile', models.FileField(null=True, upload_to='documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='JoinClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.classsubject')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.users')),
            ],
        ),
        migrations.AddField(
            model_name='classsubject',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.users'),
        ),
    ]
