# Generated by Django 5.1.1 on 2024-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_securityalert_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.ManyToManyField(related_name='absent_users', to='resources.users'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.ManyToManyField(related_name='present_users', to='resources.users'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
