# Generated by Django 5.1.1 on 2024-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_attendance_status_remove_attendance_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='classSubject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='SecurityAlert',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
